name: livekit_example
description: Example app that uses LiveKit Flutter SDK
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_background: 1.1.0
  provider: ^6.0.1
  logging: ^1.0.1
  dio: ^4.0.4
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.11

  google_fonts: ^2.1.0
  eva_icons_flutter: ^3.0.0
  flutter_svg: ^1.0.0
  retrofit: 2.0.0
  retrofit_generator: 2.0.0+1
  json_annotation: ^4.0.1
  fluttertoast: ^8.0.3

  audioplayers: ^0.20.1

  livekit_client: 0.5.7
    # git:
    #   url: https://github.com/livekit/client-sdk-flutter
    #   ref: main

  socket_io_client: ^2.0.0-beta.1-nullsafety.0
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: 2.0.0
  json_serializable: ^4.1.1

  flutter_launcher_icons: ^0.9.2
  flutter_launcher_name:
      git:
        url: https://github.com/ride4sun/flutter_launcher_name
        ref: "0.9.1"
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/app_icon_nol.png"
  image_path_android: "assets/images/app_icon_nol.png"
flutter_launcher_name:
  name: "NOL.LIVE"
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-dark.svg
    - assets/images/switchCamera.svg
    - assets/images/nol-logo.svg
    - assets/images/nol_mini_icon.svg
    - assets/images/app_icon_nol.png
    - assets/images/ic_pinned.svg
    - assets/images/ic_fullscreen.svg
    - assets/mp3/pubpub.mp3
